### ISSUE TITLE
reuse field is required in case of using opt

### ISSUE THREAD

**Issue by mrtrizer** [soimy/msdf-bmfont-xml#10]
Example:
```
const opt = {
        fieldType: 'sdf',
        reuse: false /// <<<< Without this flag you get error
    };

    generateBMFont(fontPath, opt, (error, textures, font) {
    ...
    }
```
Error:
```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1345:5)
    at generateBMFont (/.../node_modules/msdf-bmfont-xml/index.js:63:14)
   ...
```

**Comment by soimy** [comment]
Thanks for the report! I'll look into it.

**Comment by soimy** [comment]
Close via 9b689dc
