### ISSUE TITLE
canvas-prebuilt incompatible with current node.js

### ISSUE THREAD

**Issue by pirrest** [soimy/msdf-bmfont-xml#27]
internal/modules/cjs/loader.js:752
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/msdf-bmfont-xml/node_modules/canvas-prebuilt/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:752:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/msdf-bmfont-xml/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

**Comment by soimy** [comment]
Sorry about that, one of the core module `canvas-prebuilt` is deprecated. I will revert back to `canvas`

**Comment by pirrest** [comment]
Thanks! I made that change locally and it works! But would be great to see it working in release. Thank you again.

**Comment by soimy** [comment]
Closing via a61ffb377ea8c5a23c1b33d651c5591f76e8b3e1
Will be in the next release with other fixes
